version: '2'
services:
  # Wordpress
  tesseract:
    image: keloran/tesseract-base
    restart: always
    ports:
      - '80:80'
      - '2222:22'
      - '9000'
    volumes:
      - ./tesseract-backend:/app
    links:
      - data
      - rabbit

  # Database
  data:
    image: keloran/tesseract-data
    restart: always
    ports:
      - '2223:22'
      - '3306:3306'
    volumes:
      - ./tesseract-backend:/appCode

  # Rabbit MQ
  rabbit:
    restart: always
    image: rabbitmq:3-management
    ports:
      - '15672:15672'

  # MongoDB
  mongo:
      restart: always
      image: mongo

  # Static Generator
  static:
    image: keloran/tesseract-static
    restart: always
    ports:
      - '8080:80'
      - '8000:8000'
      - '2224:22'
      - '9000'
    links:
      - rabbit
      - mongo
    volumes:
      - ./tesseract-frontend:/app
